<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
| -------------------------------------------------------------------
| USER AGENT TYPES
| -------------------------------------------------------------------
| This file contains four arrays of user agent data.  It is used by the
| User Agent Class to help identify browser, platform, robot, and
| mobile device data.  The array keys are used to identify the device
| and the array values are used to set the actual name of the item.
|
*/

$platforms = array (
					'windows nt 10.0'	=> 'Windows 10',
					'windows nt 6.3'	=> 'Windows 8.1',
					'windows nt 6.2'	=> 'Windows 8',
					'windows nt 6.1'	=> 'Windows 7',
					'windows nt 6.0'	=> 'Windows Vista',
					'windows nt 6.0'	=> 'Windows Longhorn',
					'windows nt 5.2'	=> 'Windows 2003',
					'windows nt 5.0'	=> 'Windows 2000',
					'windows nt 5.1'	=> 'Windows XP',
					'windows nt 4.0'	=> 'Windows NT 4.0',
					'windows me'		=> 'Windows ME',
					'winnt4.0'			=> 'Windows NT 4.0',
					'winnt 4.0'			=> 'Windows NT',
					'winnt'				=> 'Windows NT',
					'windows 98'		=> 'Windows 98',
					'win98'				=> 'Windows 98',
					'windows 95'		=> 'Windows 95',
					'win95'				=> 'Windows 95',
					'windows'			=> 'Unknown Windows OS',
					'android'			=> 'Android',
					'blackberry'		=> 'BlackBerry',
					'iphone'			=> 'iOS',
					'ipad'				=> 'iOS',
					'ipod'				=> 'iOS',
					'ppc mac'			=> 'Power PC Mac',
					'os x'				=> 'Mac OS X',
					'ppc mac'			=> 'Power PC Mac',
					'freebsd'			=> 'FreeBSD',
					'ppc'				=> 'Macintosh',
					'macintosh|mac os x'=> 'Mac OS X',
					'mac_powerpc'		=> 'Mac OS 9',
					'linux'				=> 'Linux',
					'debian'			=> 'Debian',
					'ubuntu'			=> 'Ubuntu',
					'sunos'				=> 'Sun Solaris',
					'beos'				=> 'BeOS',
					'apachebench'		=> 'ApacheBench',
					'aix'				=> 'AIX',
					'irix'				=> 'Irix',
					'osf'				=> 'DEC OSF',
					'hp-ux'				=> 'HP-UX',
					'netbsd'			=> 'NetBSD',
					'bsdi'				=> 'BSDi',
					'openbsd'			=> 'OpenBSD',
					'gnu'				=> 'GNU/Linux',
					'unix'				=> 'Unknown Unix OS',
				);


// The order of this array should NOT be changed. Many browsers return
// multiple browser types so we want to identify the sub-type first.
$browsers = array(
					'OPR'				=> 'Opera',
					'Flock'				=> 'Flock',
					'Edge'				=> 'Spartan',
					'Chrome'			=> 'Chrome',
					// Opera 10+ always reports Opera/9.80 and appends Version/<real version> to the user agent string
					'Opera.*?Version'	=> 'Opera',
					'Opera'				=> 'Opera',
					'MSIE'				=> 'Internet Explorer',
					'Internet Explorer'	=> 'Internet Explorer',
					'Trident.* rv'		=> 'Internet Explorer',
					'Shiira'			=> 'Shiira',
					'Firefox'			=> 'Firefox',
					'Chimera'			=> 'Chimera',
					'Phoenix'			=> 'Phoenix',
					'Firebird'			=> 'Firebird',
					'Camino'			=> 'Camino',
					'Netscape'			=> 'Netscape',
					'OmniWeb'			=> 'OmniWeb',
					'Safari'			=> 'Safari',
					'Mozilla'			=> 'Mozilla',
					'Konqueror'			=> 'Konqueror',
					'icab'				=> 'iCab',
					'Lynx'				=> 'Lynx',
					'Links'				=> 'Links',
					'hotjava'			=> 'HotJava',
					'amaya'				=> 'Amaya',
					'IBrowse'			=> 'IBrowse',
					'Maxthon'			=> 'Maxthon',
					'Ubuntu'			=> 'Ubuntu Web Browser',
					'Vivaldi'			=> 'Vivaldi'
				);

$mobiles = array(
					// legacy array, old values commented out
					'mobileexplorer'	=> 'Mobile Explorer',
//					'openwave'			=> 'Open Wave',
//					'opera mini'		=> 'Opera Mini',
//					'operamini'			=> 'Opera Mini',
//					'elaine'			=> 'Palm',
					'palmsource'		=> 'Palm',
//					'digital paths'		=> 'Palm',
//					'avantgo'			=> 'Avantgo',
//					'xiino'				=> 'Xiino',
					'palmscape'			=> 'Palmscape',
//					'nokia'				=> 'Nokia',
//					'ericsson'			=> 'Ericsson',
//					'blackberry'		=> 'BlackBerry',
//					'motorola'			=> 'Motorola'

					// Phones and Manufacturers
					'motorola'			=> "Motorola",
                                        //NOKIA
                                        'rx-51 n900'                    => 'Nokia N900',
                                        'maemo rx-51'                   => 'Nokia Maemo RX-51',
                                        'maemo rx-34'                   => 'Nokia N800',
                                        'nokiainternal'                 => 'Nokia Internal',
                                        'symbian'                       => 'Nokia Symbian',
                                        'nok'                           => 'Nokia',
                                        'nokia-'                        => 'Nokia N',
					'nokia'				=> "Nokia",
					'palm'				=> "Palm",
                                        //Iplle
					'iphone'			=> "Apple iPhone",
					'ipad'				=> "iPad",
					'ipod'				=> "Apple iPod Touch",
					'sony'				=> "Sony Ericsson",
					'ericsson'			=> "Sony Ericsson",
                                        //Blackberry
                                        'stv100-4'                      => 'BlackBerry Priv',
                                        'bb10'                          => 'BlackBerry',
                                        'rim'                           => 'Blackberry',
					'blackberry'                    => "BlackBerry",
					'cocoon'			=> "O2 Cocoon",
					'blazer'			=> "Treo",
                                        //LG
                                        'p713'                          => 'LG Optimus L7II',
                                        'l-01d'                         => 'LG Optimus LTE L-01D',
                                        'l-02d'                         => 'LG PRADA phone L-02D',
                                        'l-07c'                         => 'LG Optimus Bright L-07C',
					'lg'				=> "LG",
					'amoi'				=> "Amoi",
					'xda'				=> "XDA",
					'mda'				=> "MDA",
					'vario'				=> "Vario",
					'htc'				=> "HTC",
					'google'			=> "Google mobil",
					'sharp'				=> "Sharp",
					'sie-'				=> "Siemens",
                                        //Alcatel
                                        '5015d'                         => 'Alcatel One Touch Pop 3 Dual SIM',
                                        '5051x'                         => 'Alcatel One Touch Pop 4',
                                        '6036y'                         => 'Alcatel One Touch Idol 2 mini',
                                        '6050'                          => 'Alcatel One Touch Idol 2S',
                                        '6039h'                         => 'Alcatel One Touch Idol 3',
                                        'i213'                          => 'Alcatel One Touch Pixi 7',
                                        'alcatel up'                    => 'Alcatel UP',
                                        'alcatel_'                      => 'Alcatel',
                                        'alc'                           => 'Alcatel',
					'alcatel'			=> "Alcatel",
					'benq'				=> "BenQ",
					'ipaq'				=> "HP iPaq",
                                        //Motorola
                                        'moto g'                        => 'Motorola Moto G',
                                        'motorazr'                      => 'Motorola RAZR',
                                        'motorizr'                      => 'Motorola RIZR',
                                        'mot-v360'                      => 'Motorola V360',
					'mot-'				=> "Motorola",
                                        'mot'                           => 'Motorola',
                                        'motorola'                      => 'Motorola',
					'playstation portable'=> "PlayStation Portable",
					'playstation 3'		=> 'PlayStation 3',
					'playstation vita'	=> 'PlayStation Vita',
					'hiptop'			=> "Danger Hiptop",
					'nec-'				=> "NEC",
					'panasonic'			=> "Panasonic",
					'philips'			=> "Philips",
					'sagem'				=> "Sagem",
					'sanyo'				=> "Sanyo",
					'spv'				=> "SPV",
					'zte'				=> "ZTE",
					'sendo'				=> "Sendo",
					'nintendo dsi'		=> 'Nintendo DSi',
					'nintendo ds'		=> 'Nintendo DS',
					'nintendo 3ds'		=> 'Nintendo 3DS',
					'wii'				=> 'Nintendo Wii',
					'open web'			=> 'Open Web',
					'openweb'			=> 'OpenWeb',

					// Operating Systems
					//elddenmedio add - 24-05-2017
                                        'nexus'                 => 'Nexus',
                                        //Google
                                        'glass'                 => 'Google Glass',
                                        'galaxy nexus'          => 'Google Galaxy Nexus',
                                        'pixel build'           => 'Google Pixel',
                                        'pixel xl'              => 'Google Pixel XL',
                                        'pixel c'               => 'Google Pixel C',
                                        'pixel'                 => 'Google Pixel',
                                        'google'                => 'Google',
                                        //Samsung
                                        'gt-b5330'              => 'Samsung GALAXY Chat',
                                        'gt-b5510'              => 'Samsung GALAXY Y Pro',
                                        'gt-b5512'              => 'Samsung GALAXY Y Pro Duos',
                                        'gt-b7510'              => 'Samsung GALAXY Pro',
                                        'gt-i5700'              => 'Samsung GALAXY Spica',
                                        'gt-i5801'              => 'Samsung GALAXY Apollo',
                                        'gt-i5800'              => 'Samsung GALAXY 3',
                                        'gt-i8000'              => 'Samsung Omnia II',
                                        'gt-i8150'              => 'Samsung GALAXY W',
                                        'gt-i8160'              => 'Samsung GALAXY Ace 2',
                                        'gt-i8190'              => 'Samsung GALAXY S III mini',
                                        'gt-i8200'              => 'Samsung GALAXY S III mini Value Edition',
                                        'gt-i826'               => 'Samsung GALAXY Core',
                                        'gt-i8320'              => 'Samsung H1',
                                        'gt-i855'               => 'Samsung GALAXY Win',
                                        'gt-i8580'              => 'Samsung GALAXY Core Advance',
                                        'gt-i8730'              => 'Samsung GALAXY Express',
                                        'gt-i9001'              => 'Samsung GALAXY S Plus',
                                        'gt-i9003'              => 'Samsung GALAXY SL',
                                        'gt-i9010'              => 'Samsung GALAXY S Giorgio Armani',
                                        'gt-i9070'              => 'Samsung GALAXY S Advance',
                                        'gt-i9103'              => 'Samsung GALAXY R',
                                        'gt-i9105'              => 'Samsung GALAXY S II Plus',
                                        'gt-i919'               => 'Samsung GALAXY S4 mini',
                                        'sch-i435'              => 'Samsung GALAXY S4 mini',
                                        'gt-i910'               => 'Samsung GALAXY S II',
                                        'gt-i90'                => 'Samsung GALAXY S',
                                        'gt-i9295'              => 'Samsung GALAXY S4 ACTIVE',
                                        'gt-i9300'              => 'Samsung GALAXY S III',
                                        'sch-i535'              => 'Samsung GALAXY S III',
                                        'sch-l710'              => 'Samsung GALAXY S III',
                                        'gt-i9305'              => 'Samsung GALAXY S III LTE',
                                        'SCH-R530'              => 'Samsung GALAXY S III LTE',
                                        'gt-i9505'              => 'Samsung GALAXY S4',
                                        'sch-i545'              => 'Samsung GALAXY S4',
                                        'sch-i959'              => 'Samsung GALAXY S4',
                                        'sch-r970'              => 'Samsung GALAXY S4',
                                        'galaxy-s4'             => 'Samsung GALAXY S4',
                                        'gt-i9506'              => 'Samsung GALAXY S4 with LTE+',
                                        'gt-s5280'              => 'Samsung GALAXY STAR',
                                        'gt-s5301'              => 'Samsung GALAXY POCKET Plus',
                                        'gt-s5310'              => 'Samsung GALAXY POCKET Neo',
                                        'gt-s5360'              => 'Samsung GALAXY Y Hello Kitty',
                                        'gt-s6310'              => 'Samsung GALAXY Young',
                                        'gt-s6312'              => 'Samsung GALAXY Young DUOS',
                                        'gt-s6790'              => 'Samsung GALAXY FAME Lite with NFC',
                                        'gt-s6810'              => 'Samsung GALAXY FAME',
                                        'gt-s7275'              => 'Samsung GALAXY ACE 3',
                                        'gt-s7390'              => 'Samsung GALAXY Trend Lite',
                                        'gt-s7500'              => 'Samsung GALAXY ACE Plus',
                                        'gt-s7560'              => 'Samsung GALAXY Trend',
                                        'sch-i699'              => 'Samsung GALAXY Trend',
                                        'gt-s7562'              => 'Samsung GALAXY S DUOS',
                                        'sch-i919'              => 'Samsung GALAXY S DUOS',
                                        'gt-s7580'              => 'Samsung GALAXY Trend Plus',
                                        'gt-s7582'              => 'Samsung GALAXY DUOS 2',
                                        'gt-s7710'              => 'Samsung GALAXY Xcover 2',
                                        'gt-s8500'              => 'Samsung Wave',
                                        'gt-s8530'              => 'Samsugn Wave II',
                                        'gt-s8600'              => 'Samsung Wave 3',
                                        'gt-s5380'              => 'Samsung Wave Y',
                                        'gt-s7250'              => 'Samsung Wave M',
                                        'gt-s5250'              => 'Samsung Wave 525',
                                        'gt-s5330'              => 'Samsung Wave 533',
                                        'gt-s5780'              => 'Samsung Wave 578',
                                        'gt-s7230'              => 'Samsung Wave 723',
                                        'gt-i85'                => 'Samsung GALAXY Beam',
                                        'gt-'                   => 'Samsung Galaxy',
                                        'sm-c101'               => 'Samsung GALAXY S4 zoom',
                                        'sm-c115'               => 'Samsung GALAXY K zoom',
                                        'sm-g350'               => 'Samsung GALAXY CORE Plus',
                                        'sm-g386f'              => 'Samsung GALAXY CORE LTE',
                                        'sm-g3815'              => 'Samsung GALAXY EXPRESS II',
                                        'sm-j710mn'             => 'Samsung J7 Metal',
                                        'sm-j710'               => 'Samsung J7',
                                        'sm-g800'               => 'Samsung GALAXY S5 mini',
                                        'sm-g9009d'             => 'Samsung GALAXY S5 Dual-SIM',
                                        'sm-g900'               => 'Samsung GALAXY S5',
                                        'galaxy-s5'             => 'Samsung GALAXY S5',
                                        'sm-g903f'              => 'Samsung GALAXY S5 Neo',
                                        'sm-g920f'              => 'Samsung GALAXY S6',
                                        'sm-g935f'              => 'Samsung GALAXY S7 edge',
                                        'sc-02h'                => 'Samsung GALAXY S7 edge',
                                        'sch-i200'              => 'Samsung GALAXY Stellar',
                                        'sch-i829'              => 'Samsung GALAXY Style Duos',
                                        'sgh-s730'              => 'Samsung GALAXY Discover',
                                        'sch-r740'              => 'Samsung GALAXY Discover',
                                        'sch-s738'              => 'Samsung GALAXY Centura',
                                        'isw11sc'               => 'Samsung GALAXY S II WiMAX',
                                        'vollo Vi86'            => 'Samsung vollo Vi86',
                                        'galaxy'                => 'Samsung Galaxy',
                                        'sm-'                   => 'Samsung Galaxy',
                                        'samsung'               => 'Samsung',
                                        //Sony
                                        'ericsson'              => 'Sony Ericsson',
                                        'xperia'                => 'Sony Xperia',
                                        'snoy'                  => 'Sony',
                                        //HTC
                                        'xv6975'                => 'HTC Imagio',
                                        'pg86100'               => 'HTC Evo 3G',
                                        'pc36100'               => 'HTC Evo 4G',
                                        'pj83100'               => 'HTC One X',
                                        'adr6300'               => 'HTC Droid Incredible',
                                        'adr6400L'              => 'HTC ThunderBolt',
                                        'adr6410lra'            => 'HTC Droid Incredible 3',
                                        'spv e600'              => 'HTC Excalibur',
                                        'spv e650'              => 'HTC Vox',
                                        'x525a'                 => 'HTC One X+',
                                        'nexushd2'              => 'HTC HD2',
                                        'htc'                   => 'HTC',
                                        'motorola'              => 'Motorola',
                                        //Huawei
                                        'u8500'                 => 'Huawei Ideos X2',
                                        'u8510'                 => 'Huawei Ideos X3',
                                        'u8665'                 => 'Huawei Fusion 2',
                                        'u8800'                 => 'Huawei Ideos X5',
                                        'u8818'                 => 'Huawei Ascend G300',
                                        'u8860'                 => 'Huawei Honor',
                                        'u9200'                 => 'Huawei Ascend P1',
                                        'u9500'                 => 'Huawei Ascend D1',
                                        'u9508'                 => 'Huawei Honor 2',
                                        'chm-'                  => 'Huawei Honor Play 4C',
                                        'huawei'                => 'Huawei',
                                        'lenovo'                => 'Lenovo',
                                        'xiaomi'                => 'Xiaomi',
                                        'acer'                  => 'Acer',
                                        'asus'                  => 'Asus',
                                        'oppo'                  => 'Oppo',
                                        'oneplus'               => 'Oneplus',
                                        'meizu'                 => 'Meizu',
                                        'backberry'             => 'Blackberry',
                                        'alcatel'               => 'Alcatel',
                                        'zte'                   => 'Zte',
                                        'toshiba'               => 'Toshiba',
                                        //Vodafone
                                        'vodafone 875'          => 'Vodafone Smart Mini',
                                        'vodafone_875'          => 'Vodafone Smart Mini',
                                        'vodafone 975n'         => 'Vodafone Smart 3',
                                        'vodafone_975n'         => 'Vodafone Smart 3',
                                        'vodafone 785'          => 'Vodafone Smart 4 Mini',
                                        'vodafone_785'          => 'Vodafone Smart 4 Mini',
                                        'vodafone 890n'         => 'Vodafone Smart 4 Turbo',
                                        'vodafone_890n'         => 'Vodafone Smart 4 Turbo',
                                        'vodafone 985n'         => 'Vodafone Smart 4 Power',
                                        'vodafone_985n'         => 'Vodafone Smart 4 Power',
                                        'vodafonesmartchat'     => 'Vodafone Smart Chat',
                                        'vodafone'              => 'Vodafone',
                                        //Gigabyte
                                        'gygabyte-'             => 'Gygabyte',
                                        'gigabyte'              => 'Gigabyte',
                                        'xolo'                  => 'Xolo',
                                        'lava'                  => 'Lava',
                                        'micromax'              => 'Micromax',
                                        //Microsoft
                                        'kin'                   => 'Microsoft Kin',
                                        'rm-1031'               => 'Microsfot Lumia 532',
                                        'rm-106'                => 'Microsoft Lumia 640 XL',
                                        'rm-109'                => 'Microsoft Lumia 535',
                                        'rm-1099'               => 'Microsoft Lumia 430',
                                        'rm-1109'               => 'Microsoft Lumia 640',
                                        'rm-1114'               => 'Microsoft Lumia 435',
                                        'rm-1127'               => 'Microsoft Lumia 550',
                                        'rm-1141'               => 'Microsoft Lumia 540',
                                        'rm-1154'               => 'Microsoft Lumia 650',
                                        'rm-'                   => 'Microsoft Lumia',
                                        'microsoft'             => 'Microsoft',
                                        'blue'                  => 'Blue',
                                        'gionee'                => 'Gionee',
                                        'vivo'                  => 'Vivo',
                                        'leeco'                 => 'Leeco',
                                        'panasonic'             => 'Panasonic',
                                        'hp'                    => 'Hp',
                                        'yu'                    => 'Yu',
                                        'verykool'              => 'Verykool',
                                        'maxwest'               => 'Maxwest',
                                        'plum'                  => 'Plum',
					'android'			=> 'Android',
					'symbian'			=> "Symbian",
					'SymbianOS'			=> "SymbianOS",
					'elaine'			=> "Palm",
					'palm'				=> "Palm",
					'series60'			=> "Symbian S60",
					'windows ce'		=> "Windows CE",

					// Browsers
					'obigo'				=> "Obigo",
					'netfront'			=> "Netfront Browser",
					'openwave'			=> "Openwave Browser",
					'mobilexplorer'		=> "Mobile Explorer",
					'operamini'			=> "Opera Mini",
					'opera mini'		=> "Opera Mini",

					// Other
					'digital paths'		=> "Digital Paths",
					'avantgo'			=> "AvantGo",
					'xiino'				=> "Xiino",
					'novarra'			=> "Novarra Transcoder",
					'docomo'			=> "NTT DoCoMo",
					'o2'				=> "O2",

					// Fallback
					'mobile'			=> "Generic Mobile",
					'wireless'			=> "Generic Mobile",
					'j2me'				=> "Generic Mobile",
					'midp'				=> "Generic Mobile",
					'cldc'				=> "Generic Mobile",
					'up.link'			=> "Generic Mobile",
					'up.browser'		=> "Generic Mobile",
					'smartphone'		=> "Generic Mobile",
					'cellphone'			=> "Generic Mobile"
				);

// There are hundreds of bots but these are the most common.
$robots = array(
					'googlebot'			=> 'Googlebot',
					'msnbot'			=> 'MSNBot',
					'baiduspider'		=> 'Baiduspider',
					'bingbot'			=> 'Bing',
					'slurp'				=> 'Inktomi Slurp',
					'yahoo'				=> 'Yahoo',
					'ask jeeves'		=> 'Ask Jeeves',
					'fastcrawler'		=> 'FastCrawler',
					'infoseek'			=> 'InfoSeek Robot 1.0',
					'lycos'				=> 'Lycos',
					'yandex'			=> 'YandexBot',
					'mediapartners-google'=> 'MediaPartners Google',
					'CRAZYWEBCRAWLER'	=> 'Crazy Webcrawler',
					'adsbot-google'		=> 'AdsBot Google',
					'feedfetcher-google'=> 'Feedfetcher Google',
					'curious george'	=> 'Curious George',
					'ia_archiver'		=> 'Alexa Crawler',
					'MJ12bot'			=> 'Majestic-12',
					'Uptimebot'			=> 'Uptimebot'
				);

/* End of file user_agents.php */
/* Location: ./application/config/user_agents.php */
